### PR TITLE
MEDIUM: site: add attack_threshold+immediate_block

### PR DESCRIPTION
**Pull request by daniel-corbett**
This commit brings in the latest improvements that are in go-sigsci 0.1.19 (to be released), which allows for updating the attack thresholds and/or setting the immediate block functionality.

attack_threshold can be set multiple times each for the various intervals: 1, 10, 60 (in minutes).

immediate_block is a bool, which will instruct the WAF to immediately block requests with attack signals.

This commit depends on signalsciences/go-sigsci#59 as well as a new version being issued.

### CODE REVIEW

**Comment by shawnps** [comment]
@daniel-corbett could you run a couple of commands and commit/push up the results?

```
go mod tidy
terraform fmt main.tf
```

**Comment by daniel-corbett** [comment]
> Could you run a couple of commands and push up the results?

Done both - still seeing errors in the validation. Is there something else that needs to be done?

**Comment by shawnps** [comment]
@daniel-corbett the problem is likely that the build is installing `v2.1.5` which fails to validate because it doesn't contain your resource changes.

We'll probably need to update the build to use the version of the provider from the current branch, rather than the registry.

**Comment by daniel-corbett** [comment]
@shawnps - i think i fixed it.

**Comment by shawnps** [comment]
Thanks @daniel-corbett -- LGTM

**Review by shawnps — APPROVED** [review]

**Pull request merged**
